---
title: "Final Project Preliminary EDA"
author: "Haichen Wei"
date: "Nov 15, 2020"
output: html_notebook
---


# Guiding Question

Compare the nutrition facts cereal products, Starbucks and McDonald's menu, which one is a better choice for breakfast?


# Become acquainted with your data sources


### Where did you find them?

Kaggle

### Who collected/maintains them?

• 80 Cereals: 

1. These datasets have been gathered and cleaned up by Petra Isenberg, Pierre Dragicevic and Yvonne Jansen. The original source can be found at https://perso.telecom-paristech.fr/eagan/class/igr204/datasets.

2. Chris Crawford created and maintain this dataset at Kaggle.

• Nutrition facts for Starbucks Menu:

Starbucks is the maintainer for this dataset.

• Nutrition Facts for McDonald's Menu:

McDonald's is the maintainer for this dataset.

### When & Why were they originally collected?

• Chris Crawford created the 80 cereals dataset on 2017-08-18, last updated is 
2017-10-24. He stated that "Ruin your appetite for sugary cereal with this dataset!"

• Starbucks created the dataset on 2017-07-18, last updated is 2017-07-20. This dataset includes the nutritional information for Starbucks’ food and drink menu items. 

• McDonald's created the dataset on 2017-03-03. This dataset provides a nutrition analysis of every menu item on the US McDonald's menu.

### What does a case represent in each data source, and how many total cases are available?

• 80 Cereals: each cereal's nutrition facts. It has 77 total cases. 

• Nutrition facts for Starbucks Menu: a kind of food's nutrition facts. It has 113 total cases.

• Nutrition Facts for McDonald's Menu: every menu item's nutrition facts. It has 260 total cases.

### What are some of the variables that you plan to use

Since cereals data has 16 columns, McDonald's has 24 columns, and Starbucks has 6 columns, I want to choose the common columns of them, such as name, Calories, Fat, Carb., Fiber, Protein. The cereals dataset also has type and Manufacturer, these two variables may be useful. 


# Explore intuition related to the research question


### informative plots

• Range for cereals:

1. Calories: 50-160
2. Fat(g): 0-5
3. Carb.(g): -1~23
4. Fiber(g):0-14
5. Protein(g): 1-6

• Range for Starbucks:

1. Calories: 90-650
2. Fat(g): 0-37
3. Carb.(g): 5-80
4. Fiber(g): 0-21
5. Protein(g): 1-34

• Range for McDonald's:

1. Calories: 0-1880
2. Fat(g): 0-118
3. Carb.(g): 0-141
4. Fiber(g): 0-7
5. Protein(g): 0-87

### preliminary observations

It seems like McDonald's has the highest data for all the variables, and cereal has the lowest, however, the Starbucks and McDonald's have many items, this research is for breakfast, so I may need to delete some items and recreate a new table for these two datasets. 

# Data sources

```{r}
library(tidyverse)
library(mosaic)
Cereals <- mosaic::read.file("https://www.kaggle.com/crawford/80-cereals?select=cereal.csv")
Starbucks <- mosaic::read.file("https://www.kaggle.com/starbucks/starbucks-menu?select=starbucks-menu-nutrition-food.csv")
McDonalds <- mosaic::read.file("https://www.kaggle.com/mcdonalds/nutrition-facts?select=menu.csv")
```






